version: '3.1'

services:

  #bd:
  #  container_name: mysql
  #  image: mysql:5.7
  #  restart: always
  #  environment:
  #    MYSQL_DATABASE: "food"
  #    MYSQL_USER: "admin"
  #    MYSQL_PASSWORD: "password"
  #    MYSQL_ROOT_PASSWORD: "password"
  #  ports:
  #    - 3306:3306
  #  networks: 
  #    - SA
  #  volumes:
  #    - "./DataBase/db:/var/lib/mysql"

  #  microservicio1:
  #    container_name: crearusuario
  #    image: crearusuario
  #    build:
  #      context: ./Servicio1/CrearUsuarios
  #      dockerfile: Dockerfile
  #    restart: always
  #    networks: 
  #      - SA
  #    ports:
  #      - 9005:9005
  #
  #  microservicio2:
  #    container_name: modificarusuario
  #    image: modificarusuario
  #    build:
  #      context: ./Servicio1/ModificarUsuarios
  #      dockerfile: Dockerfile
  #    restart: always
  #    networks: 
  #      - SA
  #    ports:
  #      - 9006:9006
  #
  #  
  #  microservicio3:
  #    container_name: login
  #    image: login
  #    build:
  #      context: ./Servicio1/Login
  #      dockerfile: Dockerfile
  #    restart: always
  #    networks: 
  #      - SA
  #    ports:
  #      - 9007:9007
  #
  #
  #  microservicio4:
  #    container_name: ingresarproducto
  #    image: ingresarproducto
  #    build:
  #      context: ./Servicio2/IngresarProducto
  #      dockerfile: Dockerfile
  #    restart: always
  #    networks: 
  #      - SA
  #    ports:
  #      - 9001:9001
  #
  #
  #  
  #  microservicio5:
  #    container_name: modificarproducto
  #    image: modificarproducto
  #    build:
  #      context: ./Servicio2/ModificarProducto
  #      dockerfile: Dockerfile
  #    restart: always
  #    networks: 
  #      - SA
  #    ports:
  #      - 9002:9002
  #
  #
  #  microservicio6:
  #    container_name: obtenerproducto
  #    image: obtenerproducto
  #    build:
  #      context: ./Servicio2/ObtenerProducto
  #      dockerfile: Dockerfile
  #    restart: always
  #    networks: 
  #      - SA
  #    ports:
  #      - 9003:9003
  #
  #
  #
  #  microservicio7:
  #    container_name: eliminarproducto
  #    image: eliminarproducto
  #    build:
  #      context: ./Servicio2/EliminarProducto
  #      dockerfile: Dockerfile
  #    restart: always
  #    networks: 
  #      - SA
  #    ports:
  #      - 9004:9004
  #
  #
  
  usuario:
    container_name: usuario
    image: usuario
    build:
      context: ./Usuario
      dockerfile: Dockerfile
    restart: always
    networks: 
      - SA
    ports:
      - 47001:3000


  frontend:
    container_name: frontend
    image: frontend
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    restart: always
    # environment:
    #   REACT_APP_IP_2: "35.193.209.112"
    networks: 
      - SA
    ports:
      - 47000:4200

networks: 
    SA:



  

