---
- hosts: all
  become: yes
  become_user: deploy
  tasks:
    - name: Clone app repos
      command: git clone https://github.com/echicasprado/SA-junio.git
      args:
        creates: /Compose
      loop: "compose"
      
    # .envrc will be sourced by the deploy script to set environment variables
    - name: env
      copy:
        src: ./
      loop: "Compose"
